export const SET_FEED_POSTS = 'SET_FEED_POSTS'
export const ADD_FEED_POST = 'ADD_FEED_POST'
export const SET_FEED_POST_POSTING_COMMENT_LOADING = 'SET_FEED_POST_POSTING_COMMENT_LOADING'
export const ADD_FEED_POST_COMMENT = 'ADD_FEED_POST_COMMENT'
