export const ADD_POST_REACTION_NOTIFICATION = 'ADD_POST_REACTION_NOTIFICATION'
export const SET_TOTAL_UNSEEN_REACTIONS = 'SET_TOTAL_UNSEEN_REACTIONS'
export const SET_POST_REACTION_NOTIFICATIONS = 'SET_POST_REACTION_NOTIFICATIONS'
